apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-jeanevangelista
  namespace: jeanevangelista
spec:
  storageClassName: default-storage-class-jeanevangelista
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: jeanevangelista
