apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: jeanevangelista
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30502
  type: NodePort
