apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: jeanevangelista
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 52034
      targetPort: 5000
      nodePort: 52034
  type: NodePort
