apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: jeanevangelista
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80 # The service's port
      targetPort: 5000 # The container port
      nodePort: 30080 # For NodePort
  type: NodePort
